/*
 * AUTO-GENERATED by scripts/precompute_lfsr.py
 * Drop-in replacement for lib/eth/rtl/lfsr.v
 * Uses precomputed XOR trees instead of slow Verilog function evaluation.
 * This file is used in build.sh INSTEAD of lib/eth/rtl/lfsr.v
 */

`resetall
`timescale 1ns / 1ps
`default_nettype none

module lfsr #
(
    parameter LFSR_WIDTH = 31,
    parameter LFSR_POLY = 31'h10000001,
    parameter LFSR_CONFIG = "FIBONACCI",
    parameter LFSR_FEED_FORWARD = 0,
    parameter REVERSE = 0,
    parameter DATA_WIDTH = 8,
    parameter STYLE = "AUTO"
)
(
    input  wire [DATA_WIDTH-1:0] data_in,
    input  wire [LFSR_WIDTH-1:0] state_in,
    output wire [DATA_WIDTH-1:0] data_out,
    output wire [LFSR_WIDTH-1:0] state_out
);

generate

if (LFSR_WIDTH == 32 && LFSR_POLY == 32'h4c11db7 && LFSR_CONFIG == "GALOIS" && LFSR_FEED_FORWARD == 0 && REVERSE == 1 && DATA_WIDTH == 8) begin : precomputed_32_8
    // LFSR_WIDTH=32, DATA_WIDTH=8, GALOIS, POLY=0x4c11db7, REV=True
    assign state_out[0] = state_in[2] ^ state_in[8] ^ data_in[2];
    assign state_out[1] = state_in[0] ^ state_in[3] ^ state_in[9] ^ data_in[0] ^ data_in[3];
    assign state_out[2] = state_in[0] ^ state_in[1] ^ state_in[4] ^ state_in[10] ^ data_in[0] ^ data_in[1] ^ data_in[4];
    assign state_out[3] = state_in[1] ^ state_in[2] ^ state_in[5] ^ state_in[11] ^ data_in[1] ^ data_in[2] ^ data_in[5];
    assign state_out[4] = state_in[0] ^ state_in[2] ^ state_in[3] ^ state_in[6] ^ state_in[12] ^ data_in[0] ^ data_in[2] ^ data_in[3] ^ data_in[6];
    assign state_out[5] = state_in[1] ^ state_in[3] ^ state_in[4] ^ state_in[7] ^ state_in[13] ^ data_in[1] ^ data_in[3] ^ data_in[4] ^ data_in[7];
    assign state_out[6] = state_in[4] ^ state_in[5] ^ state_in[14] ^ data_in[4] ^ data_in[5];
    assign state_out[7] = state_in[0] ^ state_in[5] ^ state_in[6] ^ state_in[15] ^ data_in[0] ^ data_in[5] ^ data_in[6];
    assign state_out[8] = state_in[1] ^ state_in[6] ^ state_in[7] ^ state_in[16] ^ data_in[1] ^ data_in[6] ^ data_in[7];
    assign state_out[9] = state_in[7] ^ state_in[17] ^ data_in[7];
    assign state_out[10] = state_in[2] ^ state_in[18] ^ data_in[2];
    assign state_out[11] = state_in[3] ^ state_in[19] ^ data_in[3];
    assign state_out[12] = state_in[0] ^ state_in[4] ^ state_in[20] ^ data_in[0] ^ data_in[4];
    assign state_out[13] = state_in[0] ^ state_in[1] ^ state_in[5] ^ state_in[21] ^ data_in[0] ^ data_in[1] ^ data_in[5];
    assign state_out[14] = state_in[1] ^ state_in[2] ^ state_in[6] ^ state_in[22] ^ data_in[1] ^ data_in[2] ^ data_in[6];
    assign state_out[15] = state_in[2] ^ state_in[3] ^ state_in[7] ^ state_in[23] ^ data_in[2] ^ data_in[3] ^ data_in[7];
    assign state_out[16] = state_in[0] ^ state_in[2] ^ state_in[3] ^ state_in[4] ^ state_in[24] ^ data_in[0] ^ data_in[2] ^ data_in[3] ^ data_in[4];
    assign state_out[17] = state_in[0] ^ state_in[1] ^ state_in[3] ^ state_in[4] ^ state_in[5] ^ state_in[25] ^ data_in[0] ^ data_in[1] ^ data_in[3] ^ data_in[4] ^ data_in[5];
    assign state_out[18] = state_in[0] ^ state_in[1] ^ state_in[2] ^ state_in[4] ^ state_in[5] ^ state_in[6] ^ state_in[26] ^ data_in[0] ^ data_in[1] ^ data_in[2] ^ data_in[4] ^ data_in[5] ^ data_in[6];
    assign state_out[19] = state_in[1] ^ state_in[2] ^ state_in[3] ^ state_in[5] ^ state_in[6] ^ state_in[7] ^ state_in[27] ^ data_in[1] ^ data_in[2] ^ data_in[3] ^ data_in[5] ^ data_in[6] ^ data_in[7];
    assign state_out[20] = state_in[3] ^ state_in[4] ^ state_in[6] ^ state_in[7] ^ state_in[28] ^ data_in[3] ^ data_in[4] ^ data_in[6] ^ data_in[7];
    assign state_out[21] = state_in[2] ^ state_in[4] ^ state_in[5] ^ state_in[7] ^ state_in[29] ^ data_in[2] ^ data_in[4] ^ data_in[5] ^ data_in[7];
    assign state_out[22] = state_in[2] ^ state_in[3] ^ state_in[5] ^ state_in[6] ^ state_in[30] ^ data_in[2] ^ data_in[3] ^ data_in[5] ^ data_in[6];
    assign state_out[23] = state_in[3] ^ state_in[4] ^ state_in[6] ^ state_in[7] ^ state_in[31] ^ data_in[3] ^ data_in[4] ^ data_in[6] ^ data_in[7];
    assign state_out[24] = state_in[0] ^ state_in[2] ^ state_in[4] ^ state_in[5] ^ state_in[7] ^ data_in[0] ^ data_in[2] ^ data_in[4] ^ data_in[5] ^ data_in[7];
    assign state_out[25] = state_in[0] ^ state_in[1] ^ state_in[2] ^ state_in[3] ^ state_in[5] ^ state_in[6] ^ data_in[0] ^ data_in[1] ^ data_in[2] ^ data_in[3] ^ data_in[5] ^ data_in[6];
    assign state_out[26] = state_in[0] ^ state_in[1] ^ state_in[2] ^ state_in[3] ^ state_in[4] ^ state_in[6] ^ state_in[7] ^ data_in[0] ^ data_in[1] ^ data_in[2] ^ data_in[3] ^ data_in[4] ^ data_in[6] ^ data_in[7];
    assign state_out[27] = state_in[1] ^ state_in[3] ^ state_in[4] ^ state_in[5] ^ state_in[7] ^ data_in[1] ^ data_in[3] ^ data_in[4] ^ data_in[5] ^ data_in[7];
    assign state_out[28] = state_in[0] ^ state_in[4] ^ state_in[5] ^ state_in[6] ^ data_in[0] ^ data_in[4] ^ data_in[5] ^ data_in[6];
    assign state_out[29] = state_in[0] ^ state_in[1] ^ state_in[5] ^ state_in[6] ^ state_in[7] ^ data_in[0] ^ data_in[1] ^ data_in[5] ^ data_in[6] ^ data_in[7];
    assign state_out[30] = state_in[0] ^ state_in[1] ^ state_in[6] ^ state_in[7] ^ data_in[0] ^ data_in[1] ^ data_in[6] ^ data_in[7];
    assign state_out[31] = state_in[1] ^ state_in[7] ^ data_in[1] ^ data_in[7];
    assign data_out[0] = state_in[0] ^ data_in[0];
    assign data_out[1] = state_in[1] ^ data_in[1];
    assign data_out[2] = state_in[2] ^ data_in[2];
    assign data_out[3] = state_in[3] ^ data_in[3];
    assign data_out[4] = state_in[4] ^ data_in[4];
    assign data_out[5] = state_in[5] ^ data_in[5];
    assign data_out[6] = state_in[0] ^ state_in[6] ^ data_in[0] ^ data_in[6];
    assign data_out[7] = state_in[1] ^ state_in[7] ^ data_in[1] ^ data_in[7];

end else if (LFSR_WIDTH == 32 && LFSR_POLY == 32'h4c11db7 && LFSR_CONFIG == "GALOIS" && LFSR_FEED_FORWARD == 0 && REVERSE == 1 && DATA_WIDTH == 32) begin : precomputed_32_32
    // LFSR_WIDTH=32, DATA_WIDTH=32, GALOIS, POLY=0x4c11db7, REV=True
    assign state_out[0] = state_in[0] ^ state_in[1] ^ state_in[2] ^ state_in[3] ^ state_in[4] ^ state_in[6] ^ state_in[7] ^ state_in[8] ^ state_in[16] ^ state_in[20] ^ state_in[22] ^ state_in[23] ^ state_in[26] ^ data_in[0] ^ data_in[1] ^ data_in[2] ^ data_in[3] ^ data_in[4] ^ data_in[6] ^ data_in[7] ^ data_in[8] ^ data_in[16] ^ data_in[20] ^ data_in[22] ^ data_in[23] ^ data_in[26];
    assign state_out[1] = state_in[1] ^ state_in[2] ^ state_in[3] ^ state_in[4] ^ state_in[5] ^ state_in[7] ^ state_in[8] ^ state_in[9] ^ state_in[17] ^ state_in[21] ^ state_in[23] ^ state_in[24] ^ state_in[27] ^ data_in[1] ^ data_in[2] ^ data_in[3] ^ data_in[4] ^ data_in[5] ^ data_in[7] ^ data_in[8] ^ data_in[9] ^ data_in[17] ^ data_in[21] ^ data_in[23] ^ data_in[24] ^ data_in[27];
    assign state_out[2] = state_in[0] ^ state_in[2] ^ state_in[3] ^ state_in[4] ^ state_in[5] ^ state_in[6] ^ state_in[8] ^ state_in[9] ^ state_in[10] ^ state_in[18] ^ state_in[22] ^ state_in[24] ^ state_in[25] ^ state_in[28] ^ data_in[0] ^ data_in[2] ^ data_in[3] ^ data_in[4] ^ data_in[5] ^ data_in[6] ^ data_in[8] ^ data_in[9] ^ data_in[10] ^ data_in[18] ^ data_in[22] ^ data_in[24] ^ data_in[25] ^ data_in[28];
    assign state_out[3] = state_in[1] ^ state_in[3] ^ state_in[4] ^ state_in[5] ^ state_in[6] ^ state_in[7] ^ state_in[9] ^ state_in[10] ^ state_in[11] ^ state_in[19] ^ state_in[23] ^ state_in[25] ^ state_in[26] ^ state_in[29] ^ data_in[1] ^ data_in[3] ^ data_in[4] ^ data_in[5] ^ data_in[6] ^ data_in[7] ^ data_in[9] ^ data_in[10] ^ data_in[11] ^ data_in[19] ^ data_in[23] ^ data_in[25] ^ data_in[26] ^ data_in[29];
    assign state_out[4] = state_in[2] ^ state_in[4] ^ state_in[5] ^ state_in[6] ^ state_in[7] ^ state_in[8] ^ state_in[10] ^ state_in[11] ^ state_in[12] ^ state_in[20] ^ state_in[24] ^ state_in[26] ^ state_in[27] ^ state_in[30] ^ data_in[2] ^ data_in[4] ^ data_in[5] ^ data_in[6] ^ data_in[7] ^ data_in[8] ^ data_in[10] ^ data_in[11] ^ data_in[12] ^ data_in[20] ^ data_in[24] ^ data_in[26] ^ data_in[27] ^ data_in[30];
    assign state_out[5] = state_in[0] ^ state_in[3] ^ state_in[5] ^ state_in[6] ^ state_in[7] ^ state_in[8] ^ state_in[9] ^ state_in[11] ^ state_in[12] ^ state_in[13] ^ state_in[21] ^ state_in[25] ^ state_in[27] ^ state_in[28] ^ state_in[31] ^ data_in[0] ^ data_in[3] ^ data_in[5] ^ data_in[6] ^ data_in[7] ^ data_in[8] ^ data_in[9] ^ data_in[11] ^ data_in[12] ^ data_in[13] ^ data_in[21] ^ data_in[25] ^ data_in[27] ^ data_in[28] ^ data_in[31];
    assign state_out[6] = state_in[0] ^ state_in[2] ^ state_in[3] ^ state_in[9] ^ state_in[10] ^ state_in[12] ^ state_in[13] ^ state_in[14] ^ state_in[16] ^ state_in[20] ^ state_in[23] ^ state_in[28] ^ state_in[29] ^ data_in[0] ^ data_in[2] ^ data_in[3] ^ data_in[9] ^ data_in[10] ^ data_in[12] ^ data_in[13] ^ data_in[14] ^ data_in[16] ^ data_in[20] ^ data_in[23] ^ data_in[28] ^ data_in[29];
    assign state_out[7] = state_in[1] ^ state_in[3] ^ state_in[4] ^ state_in[10] ^ state_in[11] ^ state_in[13] ^ state_in[14] ^ state_in[15] ^ state_in[17] ^ state_in[21] ^ state_in[24] ^ state_in[29] ^ state_in[30] ^ data_in[1] ^ data_in[3] ^ data_in[4] ^ data_in[10] ^ data_in[11] ^ data_in[13] ^ data_in[14] ^ data_in[15] ^ data_in[17] ^ data_in[21] ^ data_in[24] ^ data_in[29] ^ data_in[30];
    assign state_out[8] = state_in[0] ^ state_in[2] ^ state_in[4] ^ state_in[5] ^ state_in[11] ^ state_in[12] ^ state_in[14] ^ state_in[15] ^ state_in[16] ^ state_in[18] ^ state_in[22] ^ state_in[25] ^ state_in[30] ^ state_in[31] ^ data_in[0] ^ data_in[2] ^ data_in[4] ^ data_in[5] ^ data_in[11] ^ data_in[12] ^ data_in[14] ^ data_in[15] ^ data_in[16] ^ data_in[18] ^ data_in[22] ^ data_in[25] ^ data_in[30] ^ data_in[31];
    assign state_out[9] = state_in[0] ^ state_in[2] ^ state_in[4] ^ state_in[5] ^ state_in[7] ^ state_in[8] ^ state_in[12] ^ state_in[13] ^ state_in[15] ^ state_in[17] ^ state_in[19] ^ state_in[20] ^ state_in[22] ^ state_in[31] ^ data_in[0] ^ data_in[2] ^ data_in[4] ^ data_in[5] ^ data_in[7] ^ data_in[8] ^ data_in[12] ^ data_in[13] ^ data_in[15] ^ data_in[17] ^ data_in[19] ^ data_in[20] ^ data_in[22] ^ data_in[31];
    assign state_out[10] = state_in[0] ^ state_in[2] ^ state_in[4] ^ state_in[5] ^ state_in[7] ^ state_in[9] ^ state_in[13] ^ state_in[14] ^ state_in[18] ^ state_in[21] ^ state_in[22] ^ state_in[26] ^ data_in[0] ^ data_in[2] ^ data_in[4] ^ data_in[5] ^ data_in[7] ^ data_in[9] ^ data_in[13] ^ data_in[14] ^ data_in[18] ^ data_in[21] ^ data_in[22] ^ data_in[26];
    assign state_out[11] = state_in[1] ^ state_in[3] ^ state_in[5] ^ state_in[6] ^ state_in[8] ^ state_in[10] ^ state_in[14] ^ state_in[15] ^ state_in[19] ^ state_in[22] ^ state_in[23] ^ state_in[27] ^ data_in[1] ^ data_in[3] ^ data_in[5] ^ data_in[6] ^ data_in[8] ^ data_in[10] ^ data_in[14] ^ data_in[15] ^ data_in[19] ^ data_in[22] ^ data_in[23] ^ data_in[27];
    assign state_out[12] = state_in[2] ^ state_in[4] ^ state_in[6] ^ state_in[7] ^ state_in[9] ^ state_in[11] ^ state_in[15] ^ state_in[16] ^ state_in[20] ^ state_in[23] ^ state_in[24] ^ state_in[28] ^ data_in[2] ^ data_in[4] ^ data_in[6] ^ data_in[7] ^ data_in[9] ^ data_in[11] ^ data_in[15] ^ data_in[16] ^ data_in[20] ^ data_in[23] ^ data_in[24] ^ data_in[28];
    assign state_out[13] = state_in[0] ^ state_in[3] ^ state_in[5] ^ state_in[7] ^ state_in[8] ^ state_in[10] ^ state_in[12] ^ state_in[16] ^ state_in[17] ^ state_in[21] ^ state_in[24] ^ state_in[25] ^ state_in[29] ^ data_in[0] ^ data_in[3] ^ data_in[5] ^ data_in[7] ^ data_in[8] ^ data_in[10] ^ data_in[12] ^ data_in[16] ^ data_in[17] ^ data_in[21] ^ data_in[24] ^ data_in[25] ^ data_in[29];
    assign state_out[14] = state_in[0] ^ state_in[1] ^ state_in[4] ^ state_in[6] ^ state_in[8] ^ state_in[9] ^ state_in[11] ^ state_in[13] ^ state_in[17] ^ state_in[18] ^ state_in[22] ^ state_in[25] ^ state_in[26] ^ state_in[30] ^ data_in[0] ^ data_in[1] ^ data_in[4] ^ data_in[6] ^ data_in[8] ^ data_in[9] ^ data_in[11] ^ data_in[13] ^ data_in[17] ^ data_in[18] ^ data_in[22] ^ data_in[25] ^ data_in[26] ^ data_in[30];
    assign state_out[15] = state_in[1] ^ state_in[2] ^ state_in[5] ^ state_in[7] ^ state_in[9] ^ state_in[10] ^ state_in[12] ^ state_in[14] ^ state_in[18] ^ state_in[19] ^ state_in[23] ^ state_in[26] ^ state_in[27] ^ state_in[31] ^ data_in[1] ^ data_in[2] ^ data_in[5] ^ data_in[7] ^ data_in[9] ^ data_in[10] ^ data_in[12] ^ data_in[14] ^ data_in[18] ^ data_in[19] ^ data_in[23] ^ data_in[26] ^ data_in[27] ^ data_in[31];
    assign state_out[16] = state_in[1] ^ state_in[4] ^ state_in[7] ^ state_in[10] ^ state_in[11] ^ state_in[13] ^ state_in[15] ^ state_in[16] ^ state_in[19] ^ state_in[22] ^ state_in[23] ^ state_in[24] ^ state_in[26] ^ state_in[27] ^ state_in[28] ^ data_in[1] ^ data_in[4] ^ data_in[7] ^ data_in[10] ^ data_in[11] ^ data_in[13] ^ data_in[15] ^ data_in[16] ^ data_in[19] ^ data_in[22] ^ data_in[23] ^ data_in[24] ^ data_in[26] ^ data_in[27] ^ data_in[28];
    assign state_out[17] = state_in[2] ^ state_in[5] ^ state_in[8] ^ state_in[11] ^ state_in[12] ^ state_in[14] ^ state_in[16] ^ state_in[17] ^ state_in[20] ^ state_in[23] ^ state_in[24] ^ state_in[25] ^ state_in[27] ^ state_in[28] ^ state_in[29] ^ data_in[2] ^ data_in[5] ^ data_in[8] ^ data_in[11] ^ data_in[12] ^ data_in[14] ^ data_in[16] ^ data_in[17] ^ data_in[20] ^ data_in[23] ^ data_in[24] ^ data_in[25] ^ data_in[27] ^ data_in[28] ^ data_in[29];
    assign state_out[18] = state_in[0] ^ state_in[3] ^ state_in[6] ^ state_in[9] ^ state_in[12] ^ state_in[13] ^ state_in[15] ^ state_in[17] ^ state_in[18] ^ state_in[21] ^ state_in[24] ^ state_in[25] ^ state_in[26] ^ state_in[28] ^ state_in[29] ^ state_in[30] ^ data_in[0] ^ data_in[3] ^ data_in[6] ^ data_in[9] ^ data_in[12] ^ data_in[13] ^ data_in[15] ^ data_in[17] ^ data_in[18] ^ data_in[21] ^ data_in[24] ^ data_in[25] ^ data_in[26] ^ data_in[28] ^ data_in[29] ^ data_in[30];
    assign state_out[19] = state_in[0] ^ state_in[1] ^ state_in[4] ^ state_in[7] ^ state_in[10] ^ state_in[13] ^ state_in[14] ^ state_in[16] ^ state_in[18] ^ state_in[19] ^ state_in[22] ^ state_in[25] ^ state_in[26] ^ state_in[27] ^ state_in[29] ^ state_in[30] ^ state_in[31] ^ data_in[0] ^ data_in[1] ^ data_in[4] ^ data_in[7] ^ data_in[10] ^ data_in[13] ^ data_in[14] ^ data_in[16] ^ data_in[18] ^ data_in[19] ^ data_in[22] ^ data_in[25] ^ data_in[26] ^ data_in[27] ^ data_in[29] ^ data_in[30] ^ data_in[31];
    assign state_out[20] = state_in[0] ^ state_in[3] ^ state_in[4] ^ state_in[5] ^ state_in[6] ^ state_in[7] ^ state_in[11] ^ state_in[14] ^ state_in[15] ^ state_in[16] ^ state_in[17] ^ state_in[19] ^ state_in[22] ^ state_in[27] ^ state_in[28] ^ state_in[30] ^ state_in[31] ^ data_in[0] ^ data_in[3] ^ data_in[4] ^ data_in[5] ^ data_in[6] ^ data_in[7] ^ data_in[11] ^ data_in[14] ^ data_in[15] ^ data_in[16] ^ data_in[17] ^ data_in[19] ^ data_in[22] ^ data_in[27] ^ data_in[28] ^ data_in[30] ^ data_in[31];
    assign state_out[21] = state_in[0] ^ state_in[2] ^ state_in[3] ^ state_in[5] ^ state_in[12] ^ state_in[15] ^ state_in[17] ^ state_in[18] ^ state_in[22] ^ state_in[26] ^ state_in[28] ^ state_in[29] ^ state_in[31] ^ data_in[0] ^ data_in[2] ^ data_in[3] ^ data_in[5] ^ data_in[12] ^ data_in[15] ^ data_in[17] ^ data_in[18] ^ data_in[22] ^ data_in[26] ^ data_in[28] ^ data_in[29] ^ data_in[31];
    assign state_out[22] = state_in[2] ^ state_in[7] ^ state_in[8] ^ state_in[13] ^ state_in[18] ^ state_in[19] ^ state_in[20] ^ state_in[22] ^ state_in[26] ^ state_in[27] ^ state_in[29] ^ state_in[30] ^ data_in[2] ^ data_in[7] ^ data_in[8] ^ data_in[13] ^ data_in[18] ^ data_in[19] ^ data_in[20] ^ data_in[22] ^ data_in[26] ^ data_in[27] ^ data_in[29] ^ data_in[30];
    assign state_out[23] = state_in[0] ^ state_in[3] ^ state_in[8] ^ state_in[9] ^ state_in[14] ^ state_in[19] ^ state_in[20] ^ state_in[21] ^ state_in[23] ^ state_in[27] ^ state_in[28] ^ state_in[30] ^ state_in[31] ^ data_in[0] ^ data_in[3] ^ data_in[8] ^ data_in[9] ^ data_in[14] ^ data_in[19] ^ data_in[20] ^ data_in[21] ^ data_in[23] ^ data_in[27] ^ data_in[28] ^ data_in[30] ^ data_in[31];
    assign state_out[24] = state_in[2] ^ state_in[3] ^ state_in[6] ^ state_in[7] ^ state_in[8] ^ state_in[9] ^ state_in[10] ^ state_in[15] ^ state_in[16] ^ state_in[21] ^ state_in[23] ^ state_in[24] ^ state_in[26] ^ state_in[28] ^ state_in[29] ^ state_in[31] ^ data_in[2] ^ data_in[3] ^ data_in[6] ^ data_in[7] ^ data_in[8] ^ data_in[9] ^ data_in[10] ^ data_in[15] ^ data_in[16] ^ data_in[21] ^ data_in[23] ^ data_in[24] ^ data_in[26] ^ data_in[28] ^ data_in[29] ^ data_in[31];
    assign state_out[25] = state_in[1] ^ state_in[2] ^ state_in[6] ^ state_in[9] ^ state_in[10] ^ state_in[11] ^ state_in[17] ^ state_in[20] ^ state_in[23] ^ state_in[24] ^ state_in[25] ^ state_in[26] ^ state_in[27] ^ state_in[29] ^ state_in[30] ^ data_in[1] ^ data_in[2] ^ data_in[6] ^ data_in[9] ^ data_in[10] ^ data_in[11] ^ data_in[17] ^ data_in[20] ^ data_in[23] ^ data_in[24] ^ data_in[25] ^ data_in[26] ^ data_in[27] ^ data_in[29] ^ data_in[30];
    assign state_out[26] = state_in[2] ^ state_in[3] ^ state_in[7] ^ state_in[10] ^ state_in[11] ^ state_in[12] ^ state_in[18] ^ state_in[21] ^ state_in[24] ^ state_in[25] ^ state_in[26] ^ state_in[27] ^ state_in[28] ^ state_in[30] ^ state_in[31] ^ data_in[2] ^ data_in[3] ^ data_in[7] ^ data_in[10] ^ data_in[11] ^ data_in[12] ^ data_in[18] ^ data_in[21] ^ data_in[24] ^ data_in[25] ^ data_in[26] ^ data_in[27] ^ data_in[28] ^ data_in[30] ^ data_in[31];
    assign state_out[27] = state_in[0] ^ state_in[1] ^ state_in[2] ^ state_in[6] ^ state_in[7] ^ state_in[11] ^ state_in[12] ^ state_in[13] ^ state_in[16] ^ state_in[19] ^ state_in[20] ^ state_in[23] ^ state_in[25] ^ state_in[27] ^ state_in[28] ^ state_in[29] ^ state_in[31] ^ data_in[0] ^ data_in[1] ^ data_in[2] ^ data_in[6] ^ data_in[7] ^ data_in[11] ^ data_in[12] ^ data_in[13] ^ data_in[16] ^ data_in[19] ^ data_in[20] ^ data_in[23] ^ data_in[25] ^ data_in[27] ^ data_in[28] ^ data_in[29] ^ data_in[31];
    assign state_out[28] = state_in[0] ^ state_in[4] ^ state_in[6] ^ state_in[12] ^ state_in[13] ^ state_in[14] ^ state_in[16] ^ state_in[17] ^ state_in[21] ^ state_in[22] ^ state_in[23] ^ state_in[24] ^ state_in[28] ^ state_in[29] ^ state_in[30] ^ data_in[0] ^ data_in[4] ^ data_in[6] ^ data_in[12] ^ data_in[13] ^ data_in[14] ^ data_in[16] ^ data_in[17] ^ data_in[21] ^ data_in[22] ^ data_in[23] ^ data_in[24] ^ data_in[28] ^ data_in[29] ^ data_in[30];
    assign state_out[29] = state_in[0] ^ state_in[1] ^ state_in[5] ^ state_in[7] ^ state_in[13] ^ state_in[14] ^ state_in[15] ^ state_in[17] ^ state_in[18] ^ state_in[22] ^ state_in[23] ^ state_in[24] ^ state_in[25] ^ state_in[29] ^ state_in[30] ^ state_in[31] ^ data_in[0] ^ data_in[1] ^ data_in[5] ^ data_in[7] ^ data_in[13] ^ data_in[14] ^ data_in[15] ^ data_in[17] ^ data_in[18] ^ data_in[22] ^ data_in[23] ^ data_in[24] ^ data_in[25] ^ data_in[29] ^ data_in[30] ^ data_in[31];
    assign state_out[30] = state_in[3] ^ state_in[4] ^ state_in[7] ^ state_in[14] ^ state_in[15] ^ state_in[18] ^ state_in[19] ^ state_in[20] ^ state_in[22] ^ state_in[24] ^ state_in[25] ^ state_in[30] ^ state_in[31] ^ data_in[3] ^ data_in[4] ^ data_in[7] ^ data_in[14] ^ data_in[15] ^ data_in[18] ^ data_in[19] ^ data_in[20] ^ data_in[22] ^ data_in[24] ^ data_in[25] ^ data_in[30] ^ data_in[31];
    assign state_out[31] = state_in[0] ^ state_in[1] ^ state_in[2] ^ state_in[3] ^ state_in[5] ^ state_in[6] ^ state_in[7] ^ state_in[15] ^ state_in[19] ^ state_in[21] ^ state_in[22] ^ state_in[25] ^ state_in[31] ^ data_in[0] ^ data_in[1] ^ data_in[2] ^ data_in[3] ^ data_in[5] ^ data_in[6] ^ data_in[7] ^ data_in[15] ^ data_in[19] ^ data_in[21] ^ data_in[22] ^ data_in[25] ^ data_in[31];
    assign data_out[0] = state_in[0] ^ data_in[0];
    assign data_out[1] = state_in[1] ^ data_in[1];
    assign data_out[2] = state_in[2] ^ data_in[2];
    assign data_out[3] = state_in[3] ^ data_in[3];
    assign data_out[4] = state_in[4] ^ data_in[4];
    assign data_out[5] = state_in[5] ^ data_in[5];
    assign data_out[6] = state_in[0] ^ state_in[6] ^ data_in[0] ^ data_in[6];
    assign data_out[7] = state_in[1] ^ state_in[7] ^ data_in[1] ^ data_in[7];
    assign data_out[8] = state_in[2] ^ state_in[8] ^ data_in[2] ^ data_in[8];
    assign data_out[9] = state_in[0] ^ state_in[3] ^ state_in[9] ^ data_in[0] ^ data_in[3] ^ data_in[9];
    assign data_out[10] = state_in[0] ^ state_in[1] ^ state_in[4] ^ state_in[10] ^ data_in[0] ^ data_in[1] ^ data_in[4] ^ data_in[10];
    assign data_out[11] = state_in[1] ^ state_in[2] ^ state_in[5] ^ state_in[11] ^ data_in[1] ^ data_in[2] ^ data_in[5] ^ data_in[11];
    assign data_out[12] = state_in[0] ^ state_in[2] ^ state_in[3] ^ state_in[6] ^ state_in[12] ^ data_in[0] ^ data_in[2] ^ data_in[3] ^ data_in[6] ^ data_in[12];
    assign data_out[13] = state_in[1] ^ state_in[3] ^ state_in[4] ^ state_in[7] ^ state_in[13] ^ data_in[1] ^ data_in[3] ^ data_in[4] ^ data_in[7] ^ data_in[13];
    assign data_out[14] = state_in[2] ^ state_in[4] ^ state_in[5] ^ state_in[8] ^ state_in[14] ^ data_in[2] ^ data_in[4] ^ data_in[5] ^ data_in[8] ^ data_in[14];
    assign data_out[15] = state_in[3] ^ state_in[5] ^ state_in[6] ^ state_in[9] ^ state_in[15] ^ data_in[3] ^ data_in[5] ^ data_in[6] ^ data_in[9] ^ data_in[15];
    assign data_out[16] = state_in[0] ^ state_in[4] ^ state_in[6] ^ state_in[7] ^ state_in[10] ^ state_in[16] ^ data_in[0] ^ data_in[4] ^ data_in[6] ^ data_in[7] ^ data_in[10] ^ data_in[16];
    assign data_out[17] = state_in[1] ^ state_in[5] ^ state_in[7] ^ state_in[8] ^ state_in[11] ^ state_in[17] ^ data_in[1] ^ data_in[5] ^ data_in[7] ^ data_in[8] ^ data_in[11] ^ data_in[17];
    assign data_out[18] = state_in[2] ^ state_in[6] ^ state_in[8] ^ state_in[9] ^ state_in[12] ^ state_in[18] ^ data_in[2] ^ data_in[6] ^ data_in[8] ^ data_in[9] ^ data_in[12] ^ data_in[18];
    assign data_out[19] = state_in[3] ^ state_in[7] ^ state_in[9] ^ state_in[10] ^ state_in[13] ^ state_in[19] ^ data_in[3] ^ data_in[7] ^ data_in[9] ^ data_in[10] ^ data_in[13] ^ data_in[19];
    assign data_out[20] = state_in[4] ^ state_in[8] ^ state_in[10] ^ state_in[11] ^ state_in[14] ^ state_in[20] ^ data_in[4] ^ data_in[8] ^ data_in[10] ^ data_in[11] ^ data_in[14] ^ data_in[20];
    assign data_out[21] = state_in[5] ^ state_in[9] ^ state_in[11] ^ state_in[12] ^ state_in[15] ^ state_in[21] ^ data_in[5] ^ data_in[9] ^ data_in[11] ^ data_in[12] ^ data_in[15] ^ data_in[21];
    assign data_out[22] = state_in[6] ^ state_in[10] ^ state_in[12] ^ state_in[13] ^ state_in[16] ^ state_in[22] ^ data_in[6] ^ data_in[10] ^ data_in[12] ^ data_in[13] ^ data_in[16] ^ data_in[22];
    assign data_out[23] = state_in[7] ^ state_in[11] ^ state_in[13] ^ state_in[14] ^ state_in[17] ^ state_in[23] ^ data_in[7] ^ data_in[11] ^ data_in[13] ^ data_in[14] ^ data_in[17] ^ data_in[23];
    assign data_out[24] = state_in[0] ^ state_in[8] ^ state_in[12] ^ state_in[14] ^ state_in[15] ^ state_in[18] ^ state_in[24] ^ data_in[0] ^ data_in[8] ^ data_in[12] ^ data_in[14] ^ data_in[15] ^ data_in[18] ^ data_in[24];
    assign data_out[25] = state_in[0] ^ state_in[1] ^ state_in[9] ^ state_in[13] ^ state_in[15] ^ state_in[16] ^ state_in[19] ^ state_in[25] ^ data_in[0] ^ data_in[1] ^ data_in[9] ^ data_in[13] ^ data_in[15] ^ data_in[16] ^ data_in[19] ^ data_in[25];
    assign data_out[26] = state_in[0] ^ state_in[1] ^ state_in[2] ^ state_in[10] ^ state_in[14] ^ state_in[16] ^ state_in[17] ^ state_in[20] ^ state_in[26] ^ data_in[0] ^ data_in[1] ^ data_in[2] ^ data_in[10] ^ data_in[14] ^ data_in[16] ^ data_in[17] ^ data_in[20] ^ data_in[26];
    assign data_out[27] = state_in[1] ^ state_in[2] ^ state_in[3] ^ state_in[11] ^ state_in[15] ^ state_in[17] ^ state_in[18] ^ state_in[21] ^ state_in[27] ^ data_in[1] ^ data_in[2] ^ data_in[3] ^ data_in[11] ^ data_in[15] ^ data_in[17] ^ data_in[18] ^ data_in[21] ^ data_in[27];
    assign data_out[28] = state_in[0] ^ state_in[2] ^ state_in[3] ^ state_in[4] ^ state_in[12] ^ state_in[16] ^ state_in[18] ^ state_in[19] ^ state_in[22] ^ state_in[28] ^ data_in[0] ^ data_in[2] ^ data_in[3] ^ data_in[4] ^ data_in[12] ^ data_in[16] ^ data_in[18] ^ data_in[19] ^ data_in[22] ^ data_in[28];
    assign data_out[29] = state_in[0] ^ state_in[1] ^ state_in[3] ^ state_in[4] ^ state_in[5] ^ state_in[13] ^ state_in[17] ^ state_in[19] ^ state_in[20] ^ state_in[23] ^ state_in[29] ^ data_in[0] ^ data_in[1] ^ data_in[3] ^ data_in[4] ^ data_in[5] ^ data_in[13] ^ data_in[17] ^ data_in[19] ^ data_in[20] ^ data_in[23] ^ data_in[29];
    assign data_out[30] = state_in[0] ^ state_in[1] ^ state_in[2] ^ state_in[4] ^ state_in[5] ^ state_in[6] ^ state_in[14] ^ state_in[18] ^ state_in[20] ^ state_in[21] ^ state_in[24] ^ state_in[30] ^ data_in[0] ^ data_in[1] ^ data_in[2] ^ data_in[4] ^ data_in[5] ^ data_in[6] ^ data_in[14] ^ data_in[18] ^ data_in[20] ^ data_in[21] ^ data_in[24] ^ data_in[30];
    assign data_out[31] = state_in[0] ^ state_in[1] ^ state_in[2] ^ state_in[3] ^ state_in[5] ^ state_in[6] ^ state_in[7] ^ state_in[15] ^ state_in[19] ^ state_in[21] ^ state_in[22] ^ state_in[25] ^ state_in[31] ^ data_in[0] ^ data_in[1] ^ data_in[2] ^ data_in[3] ^ data_in[5] ^ data_in[6] ^ data_in[7] ^ data_in[15] ^ data_in[19] ^ data_in[21] ^ data_in[22] ^ data_in[25] ^ data_in[31];

end else begin : unsupported
    // Unsupported configuration — outputs forced to zero.
    // Add the required configuration to scripts/precompute_lfsr.py and regenerate.
    assign state_out = {LFSR_WIDTH{1'b0}};
    assign data_out  = {DATA_WIDTH{1'b0}};

end

endgenerate

endmodule

`resetall
